"""empty message

Revision ID: 6847b93bc55e
Revises: 4369374542c7
Create Date: 2024-02-14 15:34:25.421485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6847b93bc55e'
down_revision = '4369374542c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('test1')
        batch_op.drop_column('test2')
        batch_op.drop_column('test3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test3', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('test2', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('test1', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
