"""empty message

Revision ID: 781e5fdd019b
Revises: d680af03bfc8
Create Date: 2024-02-14 15:18:00.571822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781e5fdd019b'
down_revision = 'd680af03bfc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
