"""empty message

Revision ID: 87b60b9fc131
Revises: e4fd3bd268d3
Create Date: 2024-02-14 18:30:33.656666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b60b9fc131'
down_revision = 'e4fd3bd268d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_venue', sa.Boolean(), nullable=True))
        batch_op.drop_column('seekeing_venue')


    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('seeking_talent', type_=sa.Boolean(), existing_type=sa.String(), postgresql_using='seeking_talent::boolean')
    

    with op.batch_alter_table('artist_venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist_venue', schema=None) as batch_op:
        batch_op.drop_column('start_time')
        batch_op.drop_column('id')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('seeking_talent',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seekeing_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('seeking_venue')

    # ### end Alembic commands ###
